bytecodealliance/component-docs

- component-model/src/SUMMARY.md
- component-model/src/creating-and-consuming.md
- component-model/src/creating-and-consuming/authoring.md
- component-model/src/creating-and-consuming/composing.md
- component-model/src/creating-and-consuming/distributing.md
- component-model/src/creating-and-consuming/running.md
This is very early, just sharing it to give visibility on structure and content.
> Creating and consuming components

- component-model/src/SUMMARY.md
- component-model/src/introduction.md
Brief introduction and a slight tweak to the TOC.
> Front matter

- component-model/src/concepts.md
- component-model/src/introduction.md
> "Concepts" edit suggestions

- component-model/src/introduction.md
> Update introduction to include links

- component-model/src/creating-and-consuming/distributing.md
- component-model/src/language-support.md
> Add Links To Special Interest Groups

- CONTRIBUTING.md
Small fixes for the contributing docs:
* instruct users to change to the right directory
* add syntax highlighting for code fragments
* fix mdlint issue
> Fix markdown issues and add synax highlighting

- component-model/book.toml
Added two buttons at the top right corner to:
- Edit the page
- Link to the GitHub repository
> Updating book.toml to improve UX

- component-model/src/design/why-component-model.md
> Grammar fix

- .github/workflows/mdbook.yml
> fix(deploy): only deploy site on merge to `bytecodealliance` main

- component-model/src/design/wit.md
Mainly copied over from: https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#item-resource
Also added a handles subsection
closes #97
> wit: add resources

- component-model/src/advanced/canonical-abi.md
> Fix incorrect link to the Components page

- component-model/src/language-support/rust.md
This addresses the resources side of #139.
ETA: and the records.
> Working with records and resources in Rust

- component-model/examples/tutorial/README.md
- component-model/src/creating-and-consuming/running.md
- component-model/src/tutorial.md
a few more spots where we could be plugging
> fix: use wac plug in tutorial and running guide

- .github/workflows/mdbook.yml
- CONTRIBUTING.md
- scripts/generate_sitemap.py
CI is [breaking](https://github.com/bytecodealliance/component-docs/actions/runs/11579756125/job/32236725244#step:3:497) due to the [`mdbook-sitemap-generator`](https://github.com/rxdn/mdbook-sitemap-generator) crate we are using to generate our sitemap. That crate is fairly unmaintained and hasn't been updated in a uear. This adds a simple sitemap to do sitemap creation. It also improves upon sitemap creation, creating one with more [proper `url` (not `urls`) syntax](https://www.sitemaps.org/protocol.html#changefreqdef) and configured `priority` and `changefreq` fields.
Current sitemap: https://component-model.bytecodealliance.org/sitemap.xml
One generated with this script:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url> …
```
> Add sitemap generator script to use from GH action

- component-model/src/language-support/go.md
* Delete a confusing where I described an alternative way to write the WIT package
* Fixed the file name of the resolved WIT package
> component-model/src/language-support/go: fix go docs

- component-model/src/language-support/javascript.md
Javscript -> JavaScript
Javascript -> JavaScript
> Fix typos in javascript.md

- .github/workflows/mdbook.yml
> Bump deploy-pages action

- component-model/src/language-support/csharp.md
> Update docs to use latest componentize-dotnet

- component-model/src/language-support/csharp.md
Resolves https://github.com/bytecodealliance/component-docs/issues/216
Thanks @MendyBerger !
> fix(csharp): fix adder classname

- component-model/src/reference/videos.md
> feat: add section with video links

- component-model/src/language-support/javascript.md
This commit updates the language guide for JS
Resolves #250 
Resolves #199
> chore(lang/js): update guide
