component-model/src/SUMMARY.md
component-model/src/language-support/rust.md

@kate-goldenring while I was trying to get  `wasm-tools compose` to work, I ran into a few details about working with packages and interfaces that were outside the scope of the core language guide (well, I felt they would have overwhelmed it).  This proposes a separate page to go into that additional language-specific detail.  But if you'd prefer it to be on the language support page then  we can figure out how to structure that for sure!
(Note this has a reference to the compose page so we shouldn't merge it until that goes in... which reinforces my feeling that we should whack in what we have and then iterate...)

Deeper dive into exporting and importing interfaces in Rust

---

.github/workflows/component-model.yml
component-model/.gitignore
component-model/spin.toml

This would use Fermyon Cloud as the publishing platform - I'm not trying to force this on anyone it's just the one I know how to deploy to.
The publish workflow needs a Fermyon Cloud access token - I don't have permission to add secrets to the repo, so if this is accepted then someone else will need to create and add one.

Publish component model book

---

component-model/src/creating-and-consuming/composing.md

I've fixed some typos in component-model/src/creating-and-consuming/composing.md :)

Fix typo in composing.md

---

component-model/src/wit-overview.md

`union`s are no more. They are an ex-type.
https://github.com/WebAssembly/component-model/pull/237

Remove union types

---

component-model/src/language-support/rust.md

`cargo-component` no longer overwrites a wit packages version when creating a component. This removes that now unnecessary note.
Cargo component change: https://github.com/bytecodealliance/cargo-component/issues/111

Update Rust guide to remove `cargo-component` versioning note

---

README.md

So it's easier to find the published site from the readme.

Link from repo to rendered version

---

component-model/src/SUMMARY.md
component-model/src/creating-and-consuming/running.md
component-model/src/implementations.md
component-model/src/implementations/jco.md
component-model/src/implementations/wasmtime.md

This provides links to wasmtime (which we already had via the Running Components page) and jco, and sets up a home for linking to hosts in future.

Initial overview of implementations

---

component-model/examples/tutorial/README.md

If you follow the tutorial readme, the last command `wasm-tools compose command/target/wasm32-wasi/release/command.wasm -d composed.wasm -o command.wasm` will fail because command.wasm hasn't been built yet. This PR adds the missing command.

Add missing build command to tutorial readme

---

.gitignore
component-model/examples/example-host/Cargo.lock
component-model/examples/example-host/Cargo.toml
component-model/examples/example-host/src/add.rs
component-model/examples/tutorial/README.md
component-model/src/creating-and-consuming/running.md
component-model/src/language-support/rust.md
component-model/src/runtimes/wasmtime.md
component-model/src/tutorial.md

Since wasmtime v14.0.0, the `--wasm-features` option for `wasmtime run` has been changed to `--wasm` (or `-W`).
See https://github.com/bytecodealliance/wasmtime/pull/6925 for more information.

upgrade wasmtime to v14.0.2 and update wasmtime cli options

---

component-model/src/language-support/rust.md

The docs for installing the `cargo component` command was using the git repo and stating that there is not `crates.io` distribution of `cargo component`, which is no longer true (see [here](https://crates.io/crates/cargo-component)). This PR fixes that by documenting installing directly from `crates.io` and updating the info message.

Update cargo component install doc

---

component-model/examples/example-host/README.md
component-model/examples/example-host/add.wit
component-model/examples/tutorial/README.md
component-model/examples/tutorial/wit/calculator.wit
component-model/src/creating-and-consuming/composing.md
component-model/src/design/wit.md
component-model/src/language-support.md
component-model/src/language-support/rust.md
component-model/src/tutorial.md

With this PR all `.wit` files and inline `WIT` fragments are updated to have semicolons in place
fixes #85

Add semicolons to WIT files and samples

---

component-model/examples/tutorial/command/src/main.rs

As described in #92, the tutorial was broken when using latest wasm-tools and wasmtime 15.0.1.
By removing the sleep instruction (which was there due to a bug that I can not reproduce) the tutorial works again as expected
Worth mentioning that composing the final `command.wasm` still produces a bunch of warnings. 
However, executing the resulting module with `wasmtime run` works again as expected
fixes #92

Fix broken tutorial

---

component-model/src/design/wit.md

Wit [uses tripe-slash comments] for documentation; update a few example code blocks accordingly.
[uses tripe-slash comments]: https://github.com/WebAssembly/component-model/issues/286

Use triple-slash comments for documentation in Wit.

---

component-model/src/SUMMARY.md

The WIT section is an in-depth examination of WIT and assumes knowledge of what WIT worlds are. This PR moves the section on worlds to before the section on WIT so that users are more likely to gain that knowledge before putting it to practice by writing WIT packages.

Move the worlds section before the WIT section

---

component-model/src/design/wit.md

The `float32` and `float64` types are being
[renamed to `f32` and `f64`]. All the main tools have been updated to accept both old and new names for now, so there's no urgeny to change anything, but users who wish to can now start switching to the new `f32`/`f64` names.
While here, also add some brief documentation mentioning the handling of NaNs in `f32`/`f64`.
[renamed to `f32` and `f64`]: https://github.com/WebAssembly/component-model/issues/277

Rename `float32`/`float64` to `f32`/`f64`.

---

component-model/examples/example-host/README.md
component-model/src/SUMMARY.md
component-model/src/creating-and-consuming/authoring.md
component-model/src/language-support/go.md

Add go language guide and a description of reactor vs command components as a lot of tooling refers to the two but we haven't explicitly called out the difference anywhere
fixes https://github.com/bytecodealliance/component-docs/issues/37

Add Go language guide

---

component-model/src/runtimes/wasmtime.md

Fix a simple typo in the docs.
Did not perform any further validation (since I'm only on the web editor, and it seems as safe as a change can be).

Fix typo in wasmtime.md

---

component-model/src/introduction.md

Added missing link to Go language support on home page

---

component-model/src/language-support/go.md

patch for commands used to wasm-bindgen and wasm-tools

patch: for tinygo wasip2 support

---

component-model/src/tutorial.md

Minor fix: a missing backtick broke link rendering. This commit adds it.

Fix link in tutorial.md

---

README.md

Readme currently says that the WASI book hasn't been started. It has now been started, so the readme should be updated to direct people to it.
This PR does _not_ update the docs to mention wasi.dev, just the readme.

Mention WASI.dev in readme

---

component-model/src/SUMMARY.md
component-model/src/introduction.md
component-model/src/language-support.md
component-model/src/language-support/csharp.md

add C# language support documentation

---

component-model/book.toml
component-model/theme/head.hbs

fixes https://github.com/bytecodealliance/component-docs/issues/157 (i hope)
I verified that it updates the html of the pages to add the script in the headers

Add header to support plausible analytics

---

.github/workflows/mdbook.yml

I am using the demo from "basic usage" section of https://github.com/actions/setup-python/tree/v5/

.github/workflows/mdbook: bump python version to 3.13

---

component-model/src/creating-and-consuming/composing.md

This makes the link clickable and render better.

Make the link clickable

---

component-model/src/language-support/rust.md

closes https://github.com/bytecodealliance/component-docs/issues/188
reduces scope of the implementation that is shared in the document to clarify that a reader should use the rest of the boiler plate code generated by `cargo component`

Clarify add implementation in Rust guide

---

component-model/src/language-support/python.md

This is a follow up to https://github.com/bytecodealliance/component-docs/pull/190, which included some redundant wording.

remove redundant wording from python.md

---

component-model/src/SUMMARY.md
component-model/src/reference/useful-links.md

This PR adds a basic page for holding/accumulating additional references that help understand the component model
Resolves #12

feat: add page to hold additional references

---

component-model/src/tutorial.md

Reorganized the tutorial by restructuring content for better flow. Moved sections around and removed duplicated information, particularly in the parts describing the `adder` and `calculator` worlds. Used backticks for code expressions to improve clarity.

reorganize tutorial and remove redundant info

---

component-model/src/language-support/go.md

I made some changes to the Go example because I had issues running it in its current state:
1. Looks like the instructions for running `wit-bindgen-go` are duplicated (and the 1st one doesn't work because no project was created at the point)
2. Update `main.go` to match example values
3. Fix `--wit-package` argument to `tinygo`

Fix Go example

---

.github/workflows/mdbook.yml

Sorry Kate I misread the error message as "you're using v3 and must upgrade (to v4)" when it was actually saying "one of your things uses v3 internally so you must upgrade _that_ (as it turns out, to v3)."  Sorry for the churn.

Update artifact action maybe correctly this time

---

component-model/examples/example-host/add.c
component-model/examples/example-host/src/async_add.rs
component-model/examples/example-host/src/sync_add.rs
component-model/src/language-support/c.md

Fixes #194 
Fixed two problems with the C docs and example host:
1. wit-bindgen has changed the names of exported C functions since the docs were originally written
2. Code written against the P1 adapter in wasmtime now requires the host to explicitly add wasi to the linker, and the P1 adapter must be kept up to date with the wastime version in the `example-host` as wasmtime updates with wasi-0.2.X patch releases. 
Examples tested and working on Win11 and MacOS 14.3

Fix c docs

---

component-model/src/language-support/csharp.md

The C# examples aren't consistent with converting s32 to int and u32 to uint, leading to a broken example.
For consistency and simplicity, I've gone ahead and changed all numbers to only use unsigned integers.

C# example - don't confuse int/s32 with uint/u32

---

component-model/src/language-support/c.md
component-model/src/language-support/csharp.md
component-model/src/language-support/go.md
component-model/src/language-support/javascript.md
component-model/src/language-support/python.md

This commit introduces a hack that suppresses mdbook-linkcheck warnings for link-like alert constructs like `[!NOTE]`, until an upstream fix can be merged.

fix: hack around mdbook-linkcheck warnings

---

.github/workflows/mdbook.yml

@itowlson ... somehow `mdbook-linkcheck` wasn't installed in CI :sweat_smile:

fix(ci): install mdbook-linkcheck in CI

---

.github/workflows/mdbook.yml

This commit fixes the deploy path (which changes slightly, due to mdbook-linkcheck)

fix(ci): deploy path for book

---

.github/actions/mdbook/action.yml
.github/workflows/deploy.yml
.github/workflows/mdbook.yml
justfile
scripts/generate_sitemap.py

Was wondering how PRs could have gotten though without `mdbook-linkcheck` running...
Also @itowlson / @kate-goldenring how do ya'll feel about disabling merge-commits in favor of squash/rebase merging?

feat(ci): run mdbook on pull requests

---

component-model/src/SUMMARY.md
component-model/src/creating-and-consuming/distributing.md

closes https://github.com/bytecodealliance/component-docs/issues/203

Update distributing components section with docs on wkg

---

component-model/examples/tutorial/adder/src/lib.rs
component-model/src/language-support/rust.md

Small fix for code in examples and documentation to match variable names used in arguments.

Match variable names to arguments

---

.gitattributes

Added a `.gitattributes` file to help [github-linguist understand](https://github.com/github-linguist/linguist/blob/main/docs/overrides.md) what files are binaries or generated code.

chore(infra): Add `.gitattributes` file to repo

---

component-model/src/SUMMARY.md
component-model/src/design/component-model-concepts.md
component-model/src/introduction.md
component-model/src/language-support/rust.md

Clarify more concisely how concepts relate to each other

---

component-model/src/design/wit.md

The WIT documentation seems to reflect the old syntax of passing multi-value returns from functions. Fixed it to specify `tuple` or `record` for this.

Fix documentation for multi-value function syntax

---

component-model/src/SUMMARY.md
component-model/src/reference/faq.md

This commit adds the beginnings of an FAQ section
Resolves #120

feat: add FAQ section

---

component-model/src/language-support/javascript.md

* use `add.add`, not just `add`, in Node example
* fix "AKA" path on `reverse-string`
(See commits for more details)

Small corrections to Javascript section

---

component-model/src/SUMMARY.md
component-model/src/introduction.md
component-model/src/reference/faq.md

By way of introduction, I'm Tim Chevalier at Igalia; we're being sponsored to work on improving the component model documentation, especially with an eye towards making it more understandable by WebAssembly beginners. 
This PR reorganizes the introduction by defining WASI before it's mentioned, and making a few other changes to make the text flow better. I also changed "Component Model" to "WebAssembly Components" in the sidebar per #122. Finally, I fixed a broken link in the FAQ section.
I attempted to use semantic line breaks in my changes, but if there's a preferred style for these docs that precludes that, let me know.

Revise introduction

---

component-model/src/language-support/go.md

This has been fixed in https://github.com/bytecodealliance/go-modules/pull/298
Also see the discussion in https://github.com/bytecodealliance/go-modules/issues/297
I've re-tested today and it's working fine with the latest too (`wasm-tools@1.235.0`) 👌

Remove wasm-tools warning for Golang

---

component-model/src/design/why-component-model.md

This is following up on one of @vados-cosmonic's suggestions on https://github.com/bytecodealliance/component-docs/pull/281 .

why-component-model section: Include both file and wasm-tools output

---

component-model/src/language-support/c.md

This commit updates the C code to use the included `wasm32-wasip2-clang` binary directly for building P2 components.
Resolves #276

feat(lang/c): use wasm32-wasip2-clang binary directly

---

component-model/src/design/why-component-model.md

As requested by @vados-cosmonic in a comment on https://github.com/bytecodealliance/component-docs/pull/285

Add line breaks before/after code blocks

---

component-model/src/design/wit.md

Most of the changes here are to add semantic line breaks, but I did expand on some concepts, particularly resources.

Expand WIT overview section

---

component-model/src/language-support/python.md

This commit fixes a few issues with `componentize-py` in the Python docs and fixes the docs as well, removing a no-longer-used section.

fix(lang/py): componentize py usage

---

component-model/src/running-components/wasmtime.md

This fixes an example which uses 'add' but where the surrounding text uses 'foo' as a function name. Foo seems more thematic.
There's also a minor typo ('and' is misspelled AFAICT).

'add' to 'foo' and minor typo in wasmtime.md

---

component-model/examples/tutorial/csharp/adder/Component.cs
component-model/examples/tutorial/csharp/adder/Component2.cs
component-model/examples/tutorial/csharp/adder/Program.cs
component-model/examples/tutorial/csharp/adder/world-hostapp.wit
component-model/src/language-support/c.md
component-model/src/language-support/csharp.md
component-model/src/language-support/example-host-part1.md
component-model/src/language-support/example-host-part2.md

Added more details where necessary. Factored code examples out into separate files and included them.
Fixed a bug where the package name in the Program.cs file (in the "host-app" project) didn't match the package name in the .wit
Factored out duplicated text in "Run the component from the example host" section that also appears in the C section; included this text from separate .md files.

Revise C# language support section

---

component-model/examples/tutorial/python/app.py
component-model/examples/tutorial/python/host.py
component-model/src/language-support/python.md

* Add explicit steps to create needed directories/files
* Move code examples into separate files
* Make the "example host" section consistent with the other language support sections
* Clarify comment about `--stub-wasi` option (made it clearer that it's an option passed to `componentize-py`)

Revise Python language support section

---

component-model/src/running-components.md
component-model/src/running-components/jco.md
component-model/src/running-components/wasmtime.md

For example, changing "wit" to "WIT" and "Wasm" to "WebAssembly".

"Running Components" section: minor style changes

---

CONTRIBUTING.md

This commit adds a basic style guide to the contributing documentation, with rules around how we currently do executable code fragments.
Resolves #239

feat: document code fragment rules

---

component-model/examples/faq/example-hello.wit
component-model/examples/faq/example.wit
component-model/src/reference/faq.md

Copyedited, added semantic line breaks, moved WIT examples into separate files.

Revise FAQ

---

component-model/src/language-support/c.md

@tschneidereit wrote on the [BA Zulip](https://bytecodealliance.zulipchat.com/#narrow/channel/206238-general/topic/Emscripten.20Component.20Model.20Support/near/542487871) 
> Emscripten only supports wasip1

Emscripten does not support the component model
